image:
  name: hashicorp/terraform:0.12.9
  entrypoint:  ["/bin/sh", "-c"]

stages:
  - build
  - deploy

plan:
  stage: build
  tags:
   - blueharvest
   - terraform
  before_script:
   - terraform init -force-copy=true
  script:
   - terraform validate

publish:
  image: giannisp/node-docker-awscli:1.2.1
  stage: deploy
  when: on_success
  dependencies:
   - plan
  tags:
   - blueharvest
   - terraform
  before_script:
   - apt-get update
   - apt-get install -y zip unzip

  script:
   - zip -r aws-child-account-module.zip ./ -x .git/**\*
   - aws s3 cp aws-child-account-module.zip s3://blue-harvest-terraform/modules/child-account/aws-child-account-module.zip --acl authenticated-read